// Variable hosting the list of words
var listOfWords = [
"sean bean",
"mark addy",
"nikolaj coster-waldau",
"michelle fairley",
"lena headey",
"emilia clarke",
"iain glen",
"aidan gillen",
"harry lloyd",
"kit harington",
"sophie turner",
"maisie williams",
"richard madden",
"alfie allen",
"isaac hempstead wright",
"jack gleeson",
"rory mccann",
"peter dinklage",
"jason momoa",
"charles dance",
"liam cunningham",
"john bradley",
"natalie dormer",
"stephen dillane",
"carice van houten",
"james cosmo",
"jerome flynn",
"conleth hill",
"sibel kekilli",
"rose leslie",
"oona chaplin",
"joe dempsie",
"kristofer hivju",
"hannah murray",
"gwendoline christie",
"iwan rheon",
"indira varma",
"michiel huisman3",
"nathalie emmanuel",
"tom wlaschiha4",
"dean-charles chapman5",
"michael mcelhatton",
"jonathan pryce"
];

// Export the list of words to other hangman script(s)
module.exports = listOfWords;